geotiff_dir: tiff_files/annotations
boundaries: gaza_boundaries/GazaStrip_MunicipalBoundaries.shp
prewar_gaza: tiff_files/prewar_gaza.tif
geojson: tiff_files/annotations/snapshot-tents-2025-12-03_121923.geojson
hdf5: final_data_labelling.h5
artifact_dir: runs
loading:
  files:
    - deir_el_balah_20250315_121122_ssc10_u0002_visual_clip_file_format.tif
    - deir_el_balah_20250319_121507_ssc8_u0001_visual_clip_file_format.tif
    - netzarim_corridor_gaza_city_beit_lahiya_20250331_121449_ssc10_u0001_visual_clip.tif
    - deir_el_balah_and_nuseirat_20250326_054752_ssc2_u0002_visual_clip_file_format.tif
    - khan_yunis_20250315_065509_ssc13_u0001_visual_file_format.tif
    - gaza_city_and_jabalia_20250319_121502_ssc8_u0001_visual_clip_file_format.tif
    - khan_yunis_al_mawasi_20250214_121114_ssc6_u0002_visual_clip.tif
    - khan_yunis_20241005_062045_ssc2_u0001_visual_clip.tif
    - deir_el_balah_20250330_121424_ssc7_u0001_visual_clip.tif
    - nuseirat_20250325_055502_ssc4_u0002_visual_clip_file_format.tif
    - khan_yunis_20250316_122205_ssc6_u0001_visual_clip_file_format.tif
    - khan_yunis_20250318_065316_ssc1_u0001_visual_clip_file_format.tif
    - al_mawasi_khan_yunis_20241002_115718_ssc7_u0001_visual.tif
processing:
  step: 0.0005
  quality_thresholds:
    start_threshold: 0.2
    max_missing_end: 1.0
    min_valid_fraction: 0.9
  complete:
    - deir_el_balah_20250315_121122_ssc10_u0002_visual_clip_file_format.tif
    - netzarim_corridor_gaza_city_beit_lahiya_20250331_121449_ssc10_u0001_visual_clip.tif
    - deir_el_balah_and_nuseirat_20250326_054752_ssc2_u0002_visual_clip_file_format.tif
    - khan_yunis_20250315_065509_ssc13_u0001_visual_file_format.tif
    - gaza_city_and_jabalia_20250319_121502_ssc8_u0001_visual_clip_file_format.tif
    - deir_el_balah_20250330_121424_ssc7_u0001_visual_clip.tif
training:
  checkpoint: null # runs/20250821_134326_best_later/best_model.pth
  epochs: 10000
  batch_size: 8
  learning_rate: 0.0005
  training_frac: 0.7
  validation_frac: 0.15
prediction:
  input: processed_data.h5
  output: predictions.h5
  model: null # runs/20250821_134326_best_later/best_model.pth
