geotiff_dir: tiff_files
boundaries: gaza_boundaries/GazaStrip_MunicipalBoundaries.shp
prewar_gaza: tiff_files/prewar_gaza.tif
hdf5: no_labels.h5
loading:
  files:
    - al_maghazi_bureij_20260101_051741_ssc4_u0002_visual_clip.tif
processing:
  step: 0.0005
  quality_thresholds:
    start_threshold: 0.2
    max_missing_end: 0.2
    min_valid_fraction: 0.9
prediction:
  save_bounds: true
  input: al_maghazi_bureij_20260101_051741_ssc4_u0002_visual_clip.h5
  output: al_maghazi_bureij_20260101.json
  model: runs/20260129_084326/best_model.pth
  # Optional sampling configuration
  sample:
    enable: false        # set to false to run on all tiles
    size: 200           # number of random tiles to predict
    seed: 5            # optional random seed for reproducibility
  processing:
    agreement: false
    threshold: 0.1
    min_area: 5
    min_distance_m: 3.0
    crop_pixels: 16  # Set to radius of total receptive field
  validation_tifs: false # ideally set to false if sampling is false
