#geotiff_dir: predict_tiffs
geotiff_dir: tiff_files
boundaries: gaza_boundaries/GazaStrip_MunicipalBoundaries.shp
# geojson: tents-2025-09-19_150435.geojson
prewar_gaza: tiff_files/prewar_gaza.tif
# hdf5: no_labels.h5
hdf5: no_labels.h5
loading:
  files:
    - al_maghazi_bureij_20260101_051741_ssc4_u0002_visual_clip.tif
    # - jabalia_beit_hanoun_20260101_051741_ssc4_u0001_visual_clip.tif
    # - rafah_khan_yunis_20260101_051741_ssc4_u0003_visual_clip.tif
processing:
  step: 0.0005
  quality_thresholds:
    start_threshold: 0.2
    max_missing_end: 0.2
    min_valid_fraction: 0.9
prediction:
  save_bounds: true
  input: al_maghazi_bureij_20260101_051741_ssc4_u0002_visual_clip.h5
  output: al_maghazi_bureij_20260101.json
  model: runs/20260129_084500/best_model.pth
  # Optional sampling configuration
  sample:
    enable: true        # set to false to run on all tiles
    size: 200           # number of random tiles to predict
    seed: 5            # optional random seed for reproducibility
  processing:
    threshold: 0.2
    min_area: 5
    min_distance_m: 3.0
    crop_pixels: 16  # Set to radius of total receptive field
  validation_tifs: true
